version: "3.8"

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://shortener:shortener@db:5432/shortener
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - data:/var/lib/postgres/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=shortener
      - POSTGRES_PASSWORD=shortener
      - POSTGRES_DB=shortener

volumes:
  data: